export const TOKENS = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  EVENT_BUS: Symbol('EVENT_BUS'),
  HELLO_REPOSITORY: Symbol('HELLO_REPOSITORY'),
  HELLO_SERVICE: Symbol('HELLO_SERVICE'),
  HELLO_PROVIDER: Symbol('HELLO_PROVIDER'),
};
